version: "3.9"
services:
  api:
    build:
      dockerfile: docker/backend.Dockerfile
    ports:
      - "3000:3000"
  ui:
    build:
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
